language: python
python:
  - "3.6.4"

before_script:
  - psql -c 'create database ride_my_way;' -U postgres

services:
  - postgresql
 
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

# command to run tests
script:
  - pytest --cov=app/

after_success:
  - coveralls
  